call_parentheses = "Always"
collapse_simple_statement = "Always"
column_width = 100
indent_type = "Spaces"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"
space_after_function_names = "Never"
syntax = "All"

[sort_requires]
enabled = true
